//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Educator : Employee
{
	public virtual string Subject
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual IEnumerable<Lesson> Lesson
	{
		get;
		set;
	}

	public virtual void registerEducator(string firstName, string lastName, string nationalId, string username, string password, bool isActive, string emailAddress, string contactNumber, string subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void disableEducator(int educatorId)
	{
		throw new System.NotImplementedException();
	}

}

