//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee
{
	public virtual string username
	{
		get;
		set;
	}

	public virtual string password
	{
		get;
		set;
	}

	public virtual string firstName
	{
		get;
		set;
	}

	public virtual string lastName
	{
		get;
		set;
	}

	public virtual string contactNumber
	{
		get;
		set;
	}

	public virtual string emailAddress
	{
		get;
		set;
	}

	public virtual string nationalIdentification
	{
		get;
		set;
	}

	public virtual bool isActive
	{
		get;
		set;
	}

}

