//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Guardian
{
	public virtual string firstName
	{
		get;
		set;
	}

	public virtual string contactNumber
	{
		get;
		set;
	}

	public virtual string lastName
	{
		get;
		set;
	}

	public virtual int id
	{
		get;
		set;
	}

	public virtual bool isActive
	{
		get;
		set;
	}

	public virtual string email
	{
		get;
		set;
	}

	public virtual string address
	{
		get;
		set;
	}

	public virtual IEnumerable<Abuse> Abuse
	{
		get;
		set;
	}

	public virtual void inputGuardian(object firstName, object lastName, object contactNumber, object address, object email, object isActive)
	{
		throw new System.NotImplementedException();
	}

}

