//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lesson
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual DateTime dateTime
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual Double durationOfClass
	{
		get;
		set;
	}

	public virtual int staffId
	{
		get;
		set;
	}

	public virtual void createlesson(Double durationOfClass, string description, DateTime date, int staffId)
	{
		throw new System.NotImplementedException();
	}

}

