//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PushNotification
{
	public virtual int id
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual string message
	{
		get;
		set;
	}

	public virtual bool isSent
	{
		get;
		set;
	}

	public virtual DateTime date
	{
		get;
		set;
	}

	public virtual bool isStaff
	{
		get;
		set;
	}

	public virtual bool isStudent
	{
		get;
		set;
	}

	public virtual bool isGuardian
	{
		get;
		set;
	}

	public virtual int staffId
	{
		get;
		set;
	}

	public virtual void inputPushNotification(string message, bool isStaff, bool isStudent, bool isGuardian, bool isSent, string description, int staffId, DateTime date)
	{
		throw new System.NotImplementedException();
	}

}

